### ISSUE TITLE
LoadGlobalJavaScript embeds javascript code which crops notebook 

### ISSUE THREAD

**Issue by aprooks** [fsprojects/IfSharp#226]
If external js is loaded via LoadGlobalJavaScript whole Javascript get's embedded into a notebook, and then it won't be viewable via GitHub or nbviewer.

See repro in #224

**Comment by cgravill** [comment]
It's a choice, you can use that approach which is convenient for self-contained notebooks but you can also insert loads from a CDN.

**Comment by aprooks** [comment]
I could not make it work as self-contained anyway. Cells had to be re-run again in order for content to be rendered.

**Comment by aprooks** [comment]
Also for customizations and self-containerization suggested the approach is to save .js  files on disk and load from notebook instead of embedding js into the notebook itself. 9k extra Loc as in provided repro is not fun to read and diff.

**Comment by cgravill** [comment]
By self-contained I mean a single file so that it can be sent to others without path issues. It's not a context I would diff - personally I prefer wiping output before committing due to the Jupyter security model which is what usually causes me to have to re-run.

LoadGlobalJavaScript is a bit of hack I wrote, but it's doing what I intended it do to do. Are you proposing it do something else?

**Comment by aprooks** [comment]
I'm only suggesting to try to find a workaround for `LoadGlobalJavaScript` which will not embed the imported library in an output cell. I'm new to Jupiter programming model and could not find a solution by myself.
