### ISSUE TITLE
Cannot run commands

### ISSUE THREAD

**Issue by torbonde** [fsprojects/IfSharp#31]
I have just installed iF# as described in the readme. I then run the `ipython notebook --profile ifsharp` command, which starts up the server. At this point, all seems to be working fine. But when I open the Feature Notebook, the following is written in the console, and nothing really seems to work in the notebook itself.
```
2014-10-20 19:46:39.091 [NotebookApp] WARNING | Notebook /Feature Notebook.ipynb is not trusted
2014-10-20 19:46:39.400 [NotebookApp] ERROR | Unhandled error in API request
Traceback (most recent call last):
  File "/Users/torbonde/anaconda/lib/python2.7/site-packages/IPython/html/base/handlers.py", line 336, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/torbonde/anaconda/lib/python2.7/site-packages/IPython/html/services/sessions/handlers.py", line 65, in post
    kernel_id = km.start_kernel(path=path)
  File "/Users/torbonde/anaconda/lib/python2.7/site-packages/IPython/html/services/kernels/kernelmanager.py", line 90, in start_kernel
    kernel_id = super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Users/torbonde/anaconda/lib/python2.7/site-packages/IPython/kernel/multikernelmanager.py", line 116, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/torbonde/anaconda/lib/python2.7/site-packages/IPython/kernel/manager.py", line 217, in start_kernel
    **kw)
  File "/Users/torbonde/anaconda/lib/python2.7/site-packages/IPython/kernel/manager.py", line 173, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/torbonde/anaconda/lib/python2.7/site-packages/IPython/kernel/launcher.py", line 260, in launch_kernel
    stdin=_stdin, stdout=_stdout, stderr=_stderr, cwd=cwd, env=os.environ)
  File "/Users/torbonde/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/torbonde/anaconda/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ERROR:tornado.access:{
  "Origin": "http://localhost:8888",
  "Content-Length": "56",
  "Accept-Language": "da-dk",
  "Accept-Encoding": "gzip, deflate",
  "Connection": "keep-alive",
  "Accept": "application/json, text/javascript, */*; q=0.01",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25",
  "Host": "localhost:8888",
  "Referer": "http://localhost:8888/notebooks/Feature%20Notebook.ipynb",
  "X-Requested-With": "XMLHttpRequest",
  "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
}
ERROR:tornado.access:500 POST /api/sessions (::1) 37.50ms referer=http://localhost:8888/notebooks/Feature%20Notebook.ipynb
WARNING:tornado.access:404 GET /static/components/codemirror/mode/fsharp/fsharp.js (::1) 1.02ms referer=http://localhost:8888/notebooks/Feature%20Notebook.ipynb
```

Can anyone tell me what is going on? I should probably tell you that I am running OS X. I have a feeling this might cause the problems.

**Comment by mndrake** [comment]
I have tried on both OS X 10.10.1 Mono 3.12.0 and Ubuntu 14.04 Mono 3.12.0 and am able to find the libzmq.* (dylib/so) file.

However I get the same error below on both when I try to launch IfSharp. I am able to build and run on Windows.

I did find this issue can happen if ``fszmq`` is used outside of windows. https://github.com/zeromq/fszmq/issues/41

@cgravill and @torbonde there were no additional changes you needed to do in order to get IfSharp to work with mono?

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.Runtime.InteropServices.MarshalDirectiveException: string marshalling conversion 35 not implemented
  at (wrapper managed-to-native) fszmq.C:zmq_bind (intptr,string)
  at fszmq.SocketModule.Bind (fszmq.Socket socket, System.String address) [0x00000] in <filename unknown>:0 
  at IfSharp.Kernel.App.Start$cont@228 (System.String[] args, Microsoft.FSharp.Core.Unit unitVar) [0x00000] in <filename unknown>:0 
  at IfSharp.Kernel.App.Start (System.String[] args) [0x00000] in <filename unknown>:0 
  at IfSharpConsole.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
2015-01-24 17:01:51.721 [NotebookApp] KernelRestarter: restarting kernel (3/5)
WARNING:root:kernel 09d4a489-f1a2-4a4b-bb46-483659851b0d restarted
```

**Comment by mndrake** [comment]
I was able to get it to working (in OS X, haven't tried Ubuntu yet) by rebuilding the 3.2.7 branch of ``fszmq`` and replacing all instances of ``UnmanagedType.AnsiBStr`` with ``UnmanagedType.LPStr`` in the ``Native.fs`` as suggested by @pblasucci, and then just replacing the ``fszmq.dll`` library in the IfSharp ``bin`` folder. I would have just used the master branch, but methods have been removed/renamed and would require changes to ``IfSharp.Kernel``.

**Comment by pblasucci** [comment]
@mndrake Out of curiosity, have you tried using the 4.0.x branch of `fszmq`? It should have addressed the LPStr issue. Although you _will_ need to build it with `--define:BSD_EAGAIN` in order to run it correctly on OS X (because even agreeing on a simple error code is too much for the major OS developers).

**Comment by mndrake** [comment]
@pblasucci I was able to use the 4.0.x branch successfully building locally as well as using the latest from nuget. I'm assuming that the latest nuget package was not built with the ``--define:BSD_EAGAIN`` flag. Even though it appears to be working with the nuget .dll what is the issue with not using the compiler flag on OS X?  

@cgravill I was able to get a basic chart example working after adding and tweaking ``FSharp.Charting.Gtk`` and posted an example result in a gist (http://nbviewer.ipython.org/gist/mndrake/5d00eceea245704e8cf1). I was glad to get get something working and will post a fork when I am able to clean it up a bit. I had to create a temp file to write a png to and then read it back as a byte array, since I could not find a OxyPlot method that would write to a memory stream.

**Comment by pblasucci** [comment]
@mndrake That's terrific news! The main issue is Windows and Linux use the same value for the EAGAIN error code. However, most popular Unix systems define a different value for the same error. It's possible your code hasn't ran into this (it's definitely tucked into a small but important subset of possible scenarios). At any rate, I'm glad you got things working. Well done!

**Comment by mndrake** [comment]
Here's a fork that is working for me for OS X. I had to create a custom ``FSharp.Charting.Gtk`` fork since I was not able to get the ``Model`` internal field exposed via reflection. I will try again later, since I would prefer to just have a ``ToPng`` method in IfSharp.Kernel instead of creating one in ``Sharp.Charting.Gtk``. Figured "get it working" then others can help with the "get it right".

https://github.com/mndrake/IfSharp/tree/mono_mac
https://github.com/mndrake/FSharp.Charting

It even works in QT console!

![qtconsole](https://cloud.githubusercontent.com/assets/1476951/5970220/975e081a-a7f5-11e4-962d-a2eb45562a34.png)

**Comment by cgravill** [comment]
That looks excellent. I was having some issues with panics on interacting with GTK. I'll try working from clean and your branch to see if we can get it running on Ubuntu too.

**Comment by mndrake** [comment]
@cgravill I was able to get the following branch working on Ubuntu 14.04. I included the ``libzmq`` files so hopefully it will work by just restoring packages.  

https://github.com/mndrake/IfSharp/tree/mono_linux

**Comment by cgravill** [comment]
I think these issues have been combined and resolved in the Jupyter branch. I'll close this but feel free to open another focused issue if there are remaining issues with the Jupyter branch.
