### ISSUE TITLE
Mono support for FSharp.Charting

### ISSUE THREAD

**Issue by prosconi** [fsprojects/IfSharp#33]
It would be nice if the GTK version of FSharp.Charting is automatically used for Mono / Linux compatibility.

**Comment by mndrake** [comment]
I was wondering if trying to use one of the d3.js wrapper libraries for visualizations might be a better cross platform solution instead of FSharp.Charting(.Gtk)? I'm thinking something similar to what [rCharts](http://rcharts.io) does for R and [Shiny](http://shiny.rstudio.com). What it does is render the html & js scripts via templates. I know that you can render html, can you do the same with javascript? I'm thinking that (nvd3)[http://nvd3.org] might be a good start if possible.

**Comment by mndrake** [comment]
I guess HTML is HTML. I just embedded the required ``.js`` libraries and used the ``Util.HTML`` method. It would be some work to create an API similar to ``FSharp.Charting``, but it could be worth it.

http://nbviewer.ipython.org/gist/mndrake/1c5dc0255e93172749af

**Comment by mndrake** [comment]
I've started on a proof of concept library if anyone is interested. [NVD3.Charting](https://github.com/mndrake/NVD3.Charting)

Basic Example
--------------------
http://nbviewer.ipython.org/gist/mndrake/dbaccaf10ab71f57af3b

**Comment by mndrake** [comment]
@prosconi Here you go :) 

A little rough around the edges still, but could be the start of a cross-platform charting solution. Hope you're ok with the chosen namespace. I'm not one for creative naming.  

I switched to using [MetricsGraphics.js](http://metricsgraphicsjs.org) due to the ease of implementation.

[Example Notebook](http://nbviewer.ipython.org/github/mndrake/IfSharp.Charting/blob/master/ifsharp_charting.ipynb)

**Comment by sylvanc** [comment]
`XPlot.Plotly` and `Angara.Chart` support for cross-platform charting has been added.
