### ISSUE TITLE
Seq.sortByDescending throws FS0192

### ISSUE THREAD

**Issue by moellnitz** [fsprojects/IfSharp#85]
### Description

Calling `Seq.sortByDescending` from a Jupyter code cell throws FS0192.

### Repro steps

1. Create a code cell
2. Enter `[1 .. 10] |> Seq.sortByDescending(fun i -> i)` and hit `CTRL+Enter`
3. Observe the output below the cell

### Expected behavior

The expected output is:

`[10; 9; 8; 7; 6; 5; 4; 3; 2; 1]`

### Actual behavior

The actual output is:

`error FS0192: internal error: convMethodRef: could not bind to method`

### Known workarounds

Using `List.sortByDescending` works fine.

### Related information 

* Operating system
  - OS X El Captain
  - RHEL Server 7.2
  - Windows 10

* Branch
  - IfSharp.v3.0.0-alpha2

**Comment by cgravill** [comment]
I think this is caused by us substituting in an earlier version of FSharp.Core.dll to attempt to maintain compatibility. The Seq.sortByDescending was implemented in F# 4.0 as part of tegularizing collections

https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/ListSeqArrayAdditions.md

We've actually switched to an F# 4.0 dll in the source code version. I've also just updated our F# Compiler Services to 6.0.2 which now errors with:

`error FS0039: The value, constructor, namespace or type 'sortByDescending' is not defined`

which is a bit more explicit but means we're effectively building against F# 3.1 or earlier. I'll investigate.

**Comment by cgravill** [comment]
This was caused by the .sigdata and .optdata we were supplying not matching. I've updated these and tested on Windows 10. This should work on other platforms but will need more testing before a release.

**Comment by moellnitz** [comment]
Thanks a lot. It now behaves as expected on OS X El Captain. Regression testing with a couple of notebooks also succeeded.

**Comment by cgravill** [comment]
Thanks for the testing. We're putting together a new release so it's great to know it works well with other existing notebooks.
